title:             Medicines
email:             your-email@example.com
description:       A Blog about Medical Science.
author:            Nidhi Kunal Jha
baseurl:           "/"
url:               "http://nidhikunaljha.github.io"

# Social Profiles

github_username:
future: true

# Build settings
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
